import "server-only";

import { randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Logo uploads.
 *
 * Written under public/tai-len and served as a static file. Three rules, all
 * about the same thing — a file uploaded by one host must not become a way to
 * reach anything else:
 *
 *   the name is generated here, never taken from the upload;
 *   the type is decided by reading the first bytes, not by the sent header;
 *   the size is capped before anything touches disk.
 *
 * A host who uploads a .svg gets a refusal rather than a file: SVG is a
 * document, it can carry script, and it would be served from this app's own
 * origin.
 */

const DIR = path.join(process.cwd(), "public", "tai-len");

export const MAX_LOGO_BYTES = 2 * 1024 * 1024;

/**
 * Identifies an image from its leading bytes.
 *
 * The browser's Content-Type is a claim by whoever made the request, and
 * renaming a file changes it. These signatures are the file saying what it is.
 */
function sniff(bytes: Uint8Array): "png" | "jpg" | "webp" | null {
  if (
    bytes.length > 8 &&
    bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47
  ) {
    return "png";
  }
  if (bytes.length > 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "jpg";
  }
  if (
    bytes.length > 12 &&
    // "RIFF" .... "WEBP"
    bytes[0] === 0x52 && bytes[1] === 0x49 && bytes[2] === 0x46 && bytes[3] === 0x46 &&
    bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50
  ) {
    return "webp";
  }
  return null;
}

export type SaveResult =
  | { ok: true; filename: string }
  | { ok: false; error: string };

export async function saveLogo(file: File): Promise<SaveResult> {
  if (file.size === 0) return { ok: false, error: "Chưa chọn tệp nào." };
  if (file.size > MAX_LOGO_BYTES) {
    return { ok: false, error: "Ảnh tối đa 2 MB." };
  }

  const bytes = new Uint8Array(await file.arrayBuffer());
  const kind = sniff(bytes);
  if (!kind) {
    return {
      ok: false,
      error: "Chỉ nhận ảnh PNG, JPEG hoặc WebP. Không nhận SVG.",
    };
  }

  // Generated, not derived from what was uploaded. Nothing a host types can
  // reach this value, so there is no path to escape the directory and no way
  // for two hosts to collide.
  const filename = `${randomBytes(16).toString("hex")}.${kind}`;

  await mkdir(DIR, { recursive: true });
  await writeFile(path.join(DIR, filename), bytes);

  return { ok: true, filename };
}

/** Removes a previously saved logo. Missing files are not an error. */
export async function deleteLogo(filename: string): Promise<void> {
  // Re-checked even though every value here was generated by saveLogo: this
  // takes a string from a database row, and a row is not a promise.
  if (!/^[0-9a-f]{32}\.(png|jpg|webp)$/.test(filename)) return;
  await unlink(path.join(DIR, filename)).catch(() => {});
}
